=== karokotlowska/TI-2021-GK-5th-sem/lab/lab02/zad3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biblioteka">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dzial" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dzial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nazwadzialu" type="xs:string"/>
        <xs:element ref="ksiazka" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ksiazka">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="autor" type="xs:string" minOccurs="1" maxOccurs="2"/>
        <xs:element name="tytul" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="cena">
       		<xs:simpleType>
			<xs:restriction base="xs:integer">
			 <xs:minInclusive value="10"/>
			 <xs:maxInclusive value="200"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="autor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="imie" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="nazwisko" type="xs:string" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== karokotlowska/TI-2021-GK-5th-sem/lab/lab02/zad3.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="zad3.css"?>
<biblioteka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad3.xsd">
    <dzial>
            <nazwadzialu>Kryminalne</nazwadzialu>
            <ksiazka>
                <autor>
                	<imie>Katarzyna</imie>
                	<nazwisko>Wrona</nazwisko>
                </autor>
                <tytul>"Miasto grozy"</tytul>
                <cena>65zl</cena>
            </ksiazka>
            
            <ksiazka>
                <autor><imie>Leon</imie>
                	<nazwisko>Kanarek</nazwisko></autor>
                <tytul>"Krew"</tytul>
                <cena>55zl</cena>
            </ksiazka>

            <ksiazka>
                <autor><imie>Barbara</imie>
                	<nazwisko>Olech</nazwisko></autor>
                <tytul>"Kwiat parpoci"</tytul>
                <cena>45zl</cena>
            </ksiazka>
            <ksiazka>
	                    <autor><imie>Jerzy</imie>
	                    	<nazwisko>Jurkowski</nazwisko></autor>
	                    <tytul>"Cisza"</tytul>
	                    <cena>50zl</cena>
            </ksiazka>
            <ksiazka>
	    	                    <autor><imie>Jan</imie>
	    	                    	<nazwisko>Oberek</nazwisko></autor>
	    	                    <tytul>"Mazur"</tytul>
	    	                    <cena>53zl</cena>
            </ksiazka>
   </dzial>

   <dzial> 
            <nazwadzialu>Przygodowe</nazwadzialu>
            <ksiazka>
                <autor><imie>Hans</imie>
                	<nazwisko>Baum</nazwisko></autor>
                <tytul>"Wyprawa na oko"</tytul>
                <cena>35zl</cena>
            </ksiazka>
            
            <ksiazka>
                <autor><imie>Lara</imie>
                	<nazwisko>Smith</nazwisko></autor>
                <tytul>"Dolina prawdy"</tytul>
                <cena>20zl</cena>
            </ksiazka>

            <ksiazka>
                <autor><imie>Brad</imie>
                	<nazwisko>Lee</nazwisko></autor>
                <tytul>"Szmaragdy"</tytul>
                <cena>60zl</cena>
            </ksiazka>
    </dzial>
    
     <dzial> 
                <nazwadzialu>Harlekiny</nazwadzialu>
                <ksiazka>
                    <autor><imie>Penelope</imie>
                    	<nazwisko>Jhons</nazwisko></autor>
                    <tytul>"Odnaleziona milosc"</tytul>
                    <cena>35zl</cena>
                </ksiazka>
                
                <ksiazka>
                    <autor><imie>Anna</imie>
                    	<nazwisko>Mather</nazwisko></autor>
                    <tytul>"Niedyskrecja"</tytul>
                    <cena>20zl</cena>
                </ksiazka>
    
                <ksiazka>
                    <autor><imie>Alice</imie>
                    	<nazwisko>Robin</nazwisko></autor>
                    <tytul>"Umowa z wiatrem"</tytul>
                    <cena>60zl</cena>
                </ksiazka>
                 <ksiazka>
		                    <autor><imie>Bruce</imie>
		                    	<nazwisko>Sullen</nazwisko></autor>
		                    <tytul>"Trzeci poca≈Çunek"</tytul>
		                    <cena>60zl</cena>
                </ksiazka>
    </dzial>
</biblioteka>
